[package]
name = "yew"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
monaco = { version="0.3.0", features = ["yew-components"] }
wasm-bindgen = "0.2"
yew = "0.19"
